### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ricokahler** [ricokahler/react-style-system#27]
This is really just for me to keep track of things I still have to do. I'll be adding to this over time.

- [ ] [bug] `transformCssTemplateLiteral`: don't wrap `staticVar` expressions in template literal strings (just inline it)
- [ ] [bug] calc function not working
- [ ] [improvement] automatic detection of whether an expression can be automatically `staticVar`ed.
